### PR TITLE
Adding Create Schedule From Transaction

### PR DESCRIPTION
**Pull request by xentara1**
As discussed..
https://github.com/actualbudget/actual/pull/2222

### CODE REVIEW

**Comment by youngcw** [comment]
Ok, one last thing. Would it make more sense to put this in the schedules page instead of the bulk actions page?

**Comment by xentara1** [comment]
I thought that, but you access it via the bulk actions page. Took precedence from the link schedule docs. Happy to move if you think makes more sense in schedules. On Jan 25, 2024, at 17:57, youngcw ***@***.***> wrote:﻿
Ok, one last thing. Would it make more sense to put this in the schedules page instead of the bulk actions page?

**Comment by youngcw** [comment]
I think it makes more sense in the schedules page since most of the time it will be used with a single transaction not multiple

**Comment by youngcw** [comment]
Thanks.  Ill merge this in once we know that the current bug is fixed and the feature is working.

**Pull request merged**
