### PR TITLE
Add API docs for getLocalbudgets() and getRemoteBudgets().

### PR DESCRIPTION
**Pull request by psybers**
API docs for https://github.com/actualbudget/actual/pull/2928.

### CODE REVIEW

**Review by RubenOlsen — APPROVED** [review]
Looking good to me.

**Comment by youngcw** [comment]
Can you look at the conflicts?  Should be good otherwise

**Comment by psybers** [comment]
Not just conflicts.  Needs updated to reflect only one new method, not two.

**Comment by psybers** [comment]
@youngcw Should all be fixed now.

**Pull request merged**
