### PR TITLE
Update Docs re delete Rules

### PR DESCRIPTION
**Pull request by Kidglove57**
Update Docs re mechanics to delete Rules

### CODE REVIEW

**Comment by j-f1** [comment]
Can you add a mention that the rule editor is under More → Rules?

**Comment by Kidglove57** [comment]
Looking at the Rules document I think there are a few other places too, where the "old" Actual is referenced. Including an earlier sentence re accessing and editing Rules, which still refers to the file menu.

I will make any obvious adjustments and update.

The only place I personally use Rules very much,  is in Schedules so it is more than possible that I am not aware of some of the more advanced features. But any updating will be better than none!

**Comment by Kidglove57** [comment]
Updated as discussed. I think I have identified and replaced all the references under Rules to the old desktop "File" menu.

**Comment by Kidglove57** [comment]
As an aside, I have had a quick look through and there are still many screenshots in the Docs that need to be updated as they do not include the "More" dropdown.

**Review by j-f1 — APPROVED** [review]
Thanks!

**Comment by j-f1** [comment]
Feel free to hit merge yourself once the PR is approved :)

**Comment by Kidglove57** [comment]
@j-f1 I'm learning - slowly! All I can see is a "Squash and merge" button. Is that the one please?

**Comment by j-f1** [comment]
@Kidglove57 That’s the one!

**Pull request merged**
