### PR TITLE
Update Contributor Section - Side Bar Order

### PR DESCRIPTION
**Pull request by Kidglove57**
The purpose is to move Contributor section to the end of the Docs. Currently it appears too early and creates too much clutter for new users

### CODE REVIEW

**Comment by Kidglove57** [comment]
I am unclear as to why the preview has failed

**Comment by rich-howell** [comment]
I am not really sure this PR is suitable, why has the contributing section been moved right to the bottom of the sidebar, nested within the Help & Support category? 

This is how the sidebar looks now with your proposed change.

image
 
I think the contributor section looked fine where it was, what was the confusion that people were running into? Also what clutter did it create? It was a single collapsed header.

**Comment by Kidglove57** [comment]
I agree the Contributing section should not be nested. That is my lack of understanding as to how to use Docasuarus.

The purposes was to get new users (quite a lot of whom may be non technical) straight into setting up and using Actual. 

Contributing then logically comes  a little later in the order of things and of interest only for those with the required technical skills.

**Comment by MatissJanis** [comment]
Fixed the issues so build preview would work.

**Review by MatissJanis — APPROVED** [review]
I think moving it below-the-fold makes sense as most folks accessing the page won't be interested in the "contributing" information. They will be, however, interested in: what is this? how do I run a demo for it? once I'm happy with the demo: how do I run it for myself? And then maybe sometime later they _might_ be interested to contribute.

**Comment by MatissJanis** [comment]
For reference how others do this (since I'm literally reading the Electron docs right now..): contribution pages at the very bottom.

Screenshot 2024-01-05 at 19 35 12

**Comment by rich-howell** [comment]
> For reference how others do this (since I'm literally reading the Electron docs right now..): contribution pages at the very bottom.
> 
> 
> 
> Screenshot 2024-01-05 at 19 35 12
> 
> 

Yes but you have put it nested under Help & Support which is wrong.

**Pull request merged**
